name: deploy private-sale by ZUNO
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: supnobita/ssh-action@master
        with:
          host: 54.151.218.185
          username: ubuntu
          key: ${{ secrets.PRISALE_SECRET }}
          port: 22
          envs: GITHUB_RUN_NUMBER
          script: |
            cd code/
            rm -rf pri-sale
            git clone https://github.com/phacntt/private-sale.git
            cd pri-sale
            DOCKER_BUILDKIT=1 docker build -t pri-sale:$GITHUB_RUN_NUMBER .
            docker stop pri-sale || echo "stop container - OK"
            docker rm pri-sale || echo "remove container - OK"
            docker run -d --restart unless-stopped --name pri-sale -p 9000:9000 \
                -e NODE_ENV=${{ secrets.NODE_ENV }} \
                -e HOST=172.31.33.255 \
                pri-sale:$GITHUB_RUN_NUMBER
