name: deploy private-sale by ZUNO
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: supnobita/ssh-action@master
        with:
          host: 54.151.218.185
          username: ubuntu
          key: ${{ secrets.PRISALE_SECRET }}
          port: 22
          envs: GITHUB_RUN_NUMBER
          script: |
            cd code/
            rm -rf private-sale
            git clone https://${{ secrets.PRISALE_TOKEN_SSH }}@github.com/phacntt/private-sale.git
            cd private-sale
            DOCKER_BUILDKIT=1 docker build -t private-sale:$GITHUB_RUN_NUMBER .
            docker stop private-sale || echo "stop container - OK"
            docker rm private-sale || echo "remove container - OK"
            docker run -d --name private-sale -p 9000:9000 \
                -e NODE_ENV=${{ secrets.NODE_ENV }} \
                -e HOST=172.31.33.255 \
                -e POSTGRES_PASSWORD=${{ secrets.PRISALE_PASSWORD }} \
                -e POSTGRES_USER=${{ secrets.PRISALE_USERNAME }} \
                -e POSTGRES_DB=${{ secrets.PRISALE_DB_NAME }} \
                private-sale:$GITHUB_RUN_NUMBER
